name: 'Deploy to AWS S3'
description: 'Deploy the built website to an AWS S3 bucket.'
inputs:
  bucket-name:
    description: 'The name of the S3 bucket to deploy to. Dummy input for now'
    required: true
runs:
  using: node20
  main: 'main.js'